### ISSUE TITLE
Sakura Trees only place leaf piles on grass and dirt

### ISSUE THREAD

**Issue by Gitcurt777** [TerraformersMC/Terrestria#63]
Got a few possible bugs.

Basalt sands are unaffected by hand, shovel, type.
As stated. Basalt sands break the same speed. No matter the item or enchantment used.

Basalt rock. Unaffected by silk touch. 

Sakura trees only drop leaves on grass/dirt. Seems the leaves should fall on everything but lava or magma. Leaves don't drop on basalt or any sand.

**Comment by NeusFear** [comment]
Are you using the latest version? these should be all fixed

**Comment by coderbot16** [comment]
The last one may still be a bug but the first two should be patched by 1.0.9 or 1.0.10.

**Comment by Gitcurt777** [comment]
Using 1.0.9 but with other mods.

**Comment by NeusFear** [comment]
https://github.com/TerraformersMC/Terrestria/releases/tag/untagged-5ba561b00f4f7054453f

**Comment by coderbot16** [comment]
Try 1.0.10 and see which bugs persist

**Comment by Gitcurt777** [comment]
Will do. As soon as my internet responds. lol

**Comment by Gitcurt777** [comment]
That link is dead for me. (page not found) Curse is unresponsive to me. I'll get back to you.

**Comment by coderbot16** [comment]
Use this one, the above one was a draft https://github.com/TerraformersMC/Terrestria/releases/tag/v1.0.10

**Comment by Gitcurt777** [comment]
Confirmed.
Basalt sand now is affected by shovel, type.
Basalt Rock now gives Basalt with silk touch.

Thank you so much for your hard works and mod!

**Comment by coderbot16** [comment]
You're welcome! Glad to hear that those issues are resolved... are the Sakura leaves still problematic?

**Comment by Gitcurt777** [comment]
Just grew a Sakura on dirt near the beach. Between vanilla and basalt sands. No leaves drop.
Seems it's still a problem at least near sands. Will have to try near stone or basalt still.

**Comment by coderbot16** [comment]
Looks like the Sakura tree generator checks with isNaturalDirtOrGrass whether a block is valid for leaf pile placement, meaning that only grass or dirt (or other dirt types) will have leaf piles placed on them. This could be easily changed.

**Comment by coderbot16** [comment]
This bug has been fixed, the fix will be pushed out in the next patch.
